name: Deploy to ECS

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Project name which is gonna be the project identifier in SonarCloud'
        required: true
        type: string
      aws-region:
        description: 'AWS region'
        required: true
        type: string
        default: 'us-east-1'
      ecr-repo-url:
        description: 'ECR repository name'
        required: true
        type: string
      ms-name:
        description: 'Microservice name'
        required: true
        type: string
      task-definition-file:
        description: 'Task definition JSON file path'
        required: true
        type: string
      cluster-name:
        description: 'ECS cluster name'
        required: true
        type: string
      service-name:
        description: 'ECS service name'
        required: true
        type: string
      desired-count:
        description: 'Desired count of tasks'
        required: false
        type: number
        default: 1
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ inputs.aws-region }}

    - name: Build and push Docker image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ inputs.ecr-repo-url }}
        docker build -t ${{ inputs.ms-name }} .
        docker tag ${{ inputs.ms-name }}:latest ${{ inputs.ecr-repo-url }}/${{ inputs.ms-name }}:latest
        docker push ${{ inputs.ecr-repo-url }}/${{ inputs.ms-name }}:latest
    - name: List files
      run: ls -la
    - name: Create or update task definition
      run: |
        aws ecs register-task-definition --cli-input-json file://${{ inputs.task-definition-file }}
    
    - name: Create ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ inputs.cluster-name }} \
          --service-name ${{ inputs.service-name }} \
          --task-definition task_${{ inputs.ms-name }} \
          --desired-count ${{ inputs.desired-count }} \



